### ISSUE TITLE
Build mostly fails at MySQL install/update in state 2.

### ISSUE THREAD

**Issue by woojay** [Modis-GmbH/ModisLock-pi-gen#1]
Here's a snippet.  It has failed almost all of my attempts at this point, in one form or another.  It's just after this section;  

[07:21:51] Begin /pi-gen/stage2/01-sys-tweaks/01-run.sh

I've been trying to build w/ docker mostly.  Vagrant I tried the first time failed w/ the same error.  And nothing in the /deploy.

w.
...

```
Stopping MySQL database server: mysqld.
/bin/df: Warning: cannot read table of mounted file systems: No such file or directory
Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
invoke-rc.d: initscript mysql, action "start" failed.
dpkg: error processing package mysql-server-5.5 (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libhtml-template-perl (2.95-1) ...
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-5.5; however:
  Package mysql-server-5.5 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 mysql-server-5.5
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
Done! Your image(s) should be in deploy/
```

**Comment by chrisqwertz** [comment]
Hey, found out the same this morning. I'm using Vagrant and VirtualBox for building.

Installing the mysql-server sometimes stopped because policy-rc.d sometimes wouldn't stop mysqld. So I tried to silence the error with this:

sed -i "s/^exit 101$/exit 0/" /usr/sbin/policy-rc.d  #ignore policy-rd action forbidden error that will freeze mysql-server installation

Apparently this was the wrong way to go. I'll keep working on it tonight.

**Comment by woojay** [comment]
No problem brother.  Thanks for looking.

**Comment by chrisqwertz** [comment]
Until then you might wanna try commit 86cb34ad15d8aed0c5a0b502c85016e958e3dd36 "stick with apt-get for continuity"

**Comment by woojay** [comment]
Thank you sir.

**Comment by woojay** [comment]
All good.
